### ISSUE TITLE
Upload the compiled binary as a GitHub release

### ISSUE THREAD

**Issue by MathisMARION** [chaosBrick/SM64CollisionPatcher#1]
Hi Frame, this is Redmat527.

Some people are still using this collision patcher for their binary ROM hacks, but the way it is distributed is generally through random Discord links. I suggest to upload it here to have a single source of trust. The [SM64 hacking resources community document][1] is referencing a dead Discord link currently.

[1]: https://docs.google.com/document/d/1pSYR91UiMVKnP3PyvJiCdwRF5wNS_nZzMe-r2WPQUJk

**Comment by FramePerfection** [comment]
Ok I've made a release, I won't close the issue just yet though because of links and stuff. You can notify whoever can edit the hacking resources document about this (or do it yourself if you have the necessary rights) and close the issue once that's done :)

**Comment by FramePerfection** [comment]
Link is fixed, closing the issue
